services:
  nginx:
    container_name: nginx
    build: ./nginx/
    image: nginx:agents-923
    configs:
      - source: nginx-conf
        target: /etc/nginx/nginx.conf
    secrets:
      - ssl-cert
      - ssl-key
    ports:
      - "8080:443"
    environment:
      - ./nginx/.env
    networks:
      - agents-923
    depends_on:
      - chess
      - identity
      - client
      - pong
    volumes:
      - $HOME/data/avatars:/usr/share/nginx/html/avatars:ro

  chess:
    container_name: chess
    build: ./services/chess-server/
    image: chess:pingpon
    volumes:
      - $HOME/data:/usr/src/app/data
    networks:
      - agents-923

  identity:
    container_name: identity
    build: ./services/identity-server/
    image: identity:agents-923
    env_file:
      - ./services/identity-server/.env
    volumes:
      - $HOME/data:/var/lib/um
      - $HOME/data/avatars:/var/avatars
    networks:
      - agents-923

  client:
    container_name: client
    build: ./client/
    image: client:agents-923
    volumes:
      - ./client:/app
      - /app/node_modules
    environment:
      - DANGEROUSLY_DISABLE_HOST_CHECK=true
    networks:
      - agents-923
    depends_on:
      - identity
      - chess
      - pong

  pong:
    container_name: pong
    build: ./services/pong-server/
    image: pong:agents-923
    networks:
      - agents-923
    volumes:
      - $HOME/data/pong:/var/local

  notification:
    container_name: notification
    build: ./services/notification-server/
    image: notification:agents-923
    networks:
      - agents-923
    volumes:
      - $HOME/data/notification:/var/local

  chat:
    container_name: chat
    build: ./services/chat-server/
    image: chat:agents-923
    networks:
      - agents-923
    volumes:
      - $HOME/data/chat:/var/lib/sqlite/

networks:
  agents-923:
    driver: bridge

volumes:
  chess-data:

configs:
  nginx-conf:
    file: ./nginx/conf/nginx.conf

secrets:
  ssl-cert:
    file: $HOME/data/ssl-cert.pem
  ssl-key:
    file: $HOME/data/ssl-key.pem
