[ req ]
default_bits       = 2048
distinguished_name = req_fields
prompt = no

[ req_fields ]
C  = MA
ST = Béni Mellal-Khenifra
L  = Khouribga
O  = 1337 Coding School
OU = Coding School
CN = agents-923
emailAddress = 42.1337.ma@gmail.com
