[ req ]
default_bits       = 2048
distinguished_name = req_fields
prompt             = no

[ req_fields ]
C  = MA
ST = Béni Mellal-Khenifra
L  = Khouribga
O  = 1337 Coding School
OU = Coding School
CN = e2r10p12.1337.ma
emailAddress = 42.1337.ma@gmail.com

[ alt_names ]
DNS.1 = e2r10p12.1337.ma
IP.1  = e2r10p12.1337.ma
